on: [push, pull_request]

name: Continuous Integration

jobs:
  check:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -Dwarnings
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Set up Rust
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
